// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use diesel::Queryable;
use serde::Serialize;
use chrono::{NaiveDateTime};

#[derive(Queryable, Debug, Serialize)]
pub struct Article {
    pub id: i32,
    pub user_id: i32,
    pub title: String,
    pub content: String,
    pub created_by: Option<i32>,
    pub created_on: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug, Serialize)]
pub struct User {
    pub id: i32,
    pub first_name: String,
    pub last_name: String,
}

